# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: ComponentGovernanceComponentDetection@0
  inputs:
    sourceScanPath: 'src/Router/RouterFunction.cs,src/ActilityLoRaEdgeDecoder/LoRaEdgeDecoderActility/__init__.py,src/HeliumLoRaEdgeDecoder/LoRaEdgeDecoderHelium/__init__.py,src/TTNLoRaEdgeDecoder/LoReEdgeDecoderTTN/__init__.py'
  displayName: 'Run Component Governance Component Detection'
